# Generated by Django 5.2.6 on 2025-09-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('ldap_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department_year', models.CharField(max_length=10)),
                ('programme', models.CharField(max_length=20)),
                ('interests', models.CharField(blank=True, max_length=300)),
                ('participation_type', models.CharField(max_length=10)),
                ('any_question', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
